from datetime import datetime
from typing import Protocol, List, Optional, Dict, Any
from app.domain.auth import User, DeviceFingerprint
from app.domain.portfolio import TaxLot, Position, PerformanceSnapshot
from app.domain.orders import Order, OrderPreview
from app.domain.money import Beneficiary, Transfer
from app.domain.aml import AMLAlert

class IUserRepository(Protocol):
    def get_by_id(self, user_id: str) -> Optional[User]: ...
    def get_by_username(self, username: str) -> Optional[User]: ...
    def get_password_hash(self, username: str) -> Optional[str]: ...
    def save_user(self, user: User, password_hash: str) -> None: ...
    def get_device_fingerprint(self, user_id: str, device_id: str) -> Optional[DeviceFingerprint]: ...
    def save_device_fingerprint(self, user_id: str, fingerprint: DeviceFingerprint) -> None: ...
    def get_recent_profile_changes_count(self, user_id: str, window_hours: int) -> int: ...
    def log_profile_change(self, user_id: str, change_type: str) -> None: ...
    
    # Account access verification BE-009
    def verify_account_access(self, party_id: str, account_id: str) -> bool: ...
    def create_account_access(self, party_id: str, account_id: str, role: str) -> None: ...


class IPortfolioRepository(Protocol):
    def save_positions(self, account_id: str, positions: List[Position]) -> None: ...
    def get_positions_by_account(self, account_id: str) -> List[Position]: ...
    def save_performance_snapshot(self, snapshot: PerformanceSnapshot) -> None: ...
    def get_tax_lots(self, account_id: str, instrument_id: str) -> List[TaxLot]: ...
    def get_cash_balances(self, account_id: str) -> Dict[str, Any]: ...


class IOrderRepository(Protocol):
    def save_order_preview(self, preview: OrderPreview) -> None: ...
    def get_order_preview(self, preview_token: str) -> Optional[OrderPreview]: ...
    def save_order(self, order: Order) -> None: ...
    def get_order_by_id(self, order_id: str) -> Optional[Order]: ...
    def get_order_by_idempotency_key(self, idempotency_key: str) -> Optional[Order]: ...
    def update_order_status(self, order_id: str, status: str, filled_at: Optional[datetime] = None, average_filled_price: Optional[float] = None) -> None: ...


class IMoneyRepository(Protocol):
    def save_beneficiary(self, beneficiary: Beneficiary) -> None: ...
    def get_beneficiary_by_account_and_clabe(self, account_id: str, clabe: str) -> Optional[Beneficiary]: ...
    def get_beneficiary_by_id(self, beneficiary_id: str) -> Optional[Beneficiary]: ...
    def get_beneficiaries(self, account_id: str) -> List[Beneficiary]: ...
    def create_transfer(self, transfer: Transfer) -> None: ...
    def get_transfer_by_idempotency_key(self, idempotency_key: str) -> Optional[Transfer]: ...


class IAMLRepository(Protocol):
    def log_aml_alert(self, alert: AMLAlert) -> None: ...
    def get_transaction_volume_window(self, account_id: str, window_hours: int) -> float: ...
    def get_last_funding_time(self, account_id: str) -> Optional[datetime]: ...
